// lib/midiakit-default.js — seed/fallback data for /midiakit, used when the
// KV store is empty. Refreshed weekly by a scheduled job that pulls fresh
// Instagram Insights (via Windsor.ai) and POSTs to /api/midiakit-data.

const DEFAULT_MIDIAKIT_DATA = {
  updatedAt: "2026-08-18T00:00:00.000Z",
  profile: {
    name: "Gabriel Siqueira",
    role: "Fotógrafo · Filmmaker · Coffee Creator",
    handle: "@gabrielnocafe",
    followers: 4114,
    following: 443,
    mediaCount: 33,
    email: "contato@gabrielnafoto.com.br",
    instagramCoffee: "@gabrielnocafe",
    instagramPhoto: "@gabrielnafoto",
    site: "gabrielnocafe.vercel.app",
  },
  window90d: {
    accountsEngaged: 36001,
    likes: 38761,
    comments: 2112,
    saves: 7361,
    shares: 4626,
    reposts: 767,
    totalInteractions: 58782,
    views: 660218,
  },
  averages: {
    reachPerReel: 6036,
    engagementPerPost: 693,
    viewsPerReel: 8191,
    engagementRatePct: 16.9,
  },
  audience: {
    gender: [
      { label: "Masculino", pct: 64.7 },
      { label: "Feminino", pct: 20.6 },
      { label: "Não informado", pct: 14.7 },
    ],
    age: [
      { label: "25–34 anos", pct: 60.1 },
      { label: "35–44 anos", pct: 25.2 },
      { label: "18–24 anos", pct: 9.8 },
      { label: "45+ anos", pct: 4.4 },
    ],
    countries: [
      { label: "🇧🇷 Brasil", value: 1598 },
      { label: "🇲🇽 México", value: 206 },
      { label: "🇺🇸 Estados Unidos", value: 202 },
      { label: "🇨🇴 Colômbia", value: 182 },
      { label: "🇮🇩 Indonésia", value: 129 },
      { label: "🇮🇷 Irã", value: 99 },
    ],
    cities: [
      { label: "São Paulo", value: 269 },
      { label: "Recife", value: 169 },
      { label: "Lima", value: 59 },
      { label: "Rio de Janeiro", value: 58 },
    ],
  },
  topPosts: [
    {
      rank: "01",
      caption: "Descobri que fazer café ouvindo música e filmando aumenta em 73% as chances de esquecer que você tem boletos pra pagar.",
      reach: 41878,
      views: 54306,
      saves: 1227,
      date: "2026-07-29",
      note: "Não the Same Café / Timemore",
      permalink: "https://www.instagram.com/reel/DbZHZIAukVU/",
      thumbnail: "/midiakit/thumb-01.jpg",
    },
    {
      rank: "02",
      caption: "POV: você chama um amigo pra tomar café e, cinco minutos depois, já tá inserido nas ideias caóticas.",
      reach: 37094,
      views: 49037,
      saves: 713,
      date: "2026-07-17",
      note: "",
      permalink: "https://www.instagram.com/reel/Da6byKLOmad/",
      thumbnail: "/midiakit/thumb-02.jpg",
    },
    {
      rank: "03",
      caption: "\"É café ou química?\" — abertura da série educativa sobre café especial.",
      reach: 17054,
      views: 21178,
      saves: 189,
      date: "2026-08-06",
      note: "",
      permalink: "https://www.instagram.com/reel/Dbt7jbjuY43/",
      thumbnail: "/midiakit/thumb-03.jpg",
    },
    {
      rank: "04",
      caption: "Start na semana com um good coffee e uma good música.",
      reach: 13532,
      views: 18467,
      saves: 129,
      date: "2026-07-27",
      note: "",
      permalink: "https://www.instagram.com/reel/DbT9RUXuaSK/",
      thumbnail: "/midiakit/thumb-04.jpg",
    },
    {
      rank: "05",
      caption: "Como explicar que minha cabeça funciona assim 24hrs por dia?",
      reach: 11069,
      views: 16032,
      saves: 226,
      date: "2026-07-22",
      note: "",
      permalink: "https://www.instagram.com/reel/DbHG9MluyrP/",
      thumbnail: "/midiakit/thumb-05.jpg",
    },
    {
      rank: "06",
      caption: "\"Uma obra de arte.\" — review em vídeo da Gaggia e24.",
      reach: 8578,
      views: 11123,
      saves: 102,
      date: "2026-07-06",
      note: "@gaggiabrasil",
      permalink: "https://www.instagram.com/reel/DadzHTJOCnX/",
      thumbnail: "/midiakit/thumb-06.jpg",
    },
  ],
  brands: [
    "Gaggia Brasil", "Timemore", "Veraz Cafés", "Dropit",
    "Not the Same Café", "Café Filomena Estefania", "O Seu Una", "São Paulo Coffee Festival",
  ],
};

module.exports = { DEFAULT_MIDIAKIT_DATA };
